DOMAIN = "mqtt_media_bridge"
DEFAULT_NAME = "MQTT Media Bridge"

# Define topics for the media player
CONF_MEDIA_ALBUM_NAME_TOPIC = "media_album_name_topic"
CONF_MEDIA_ARTIST_TOPIC = "media_artist_topic"
CONF_MEDIA_DURATION_TOPIC = "media_duration_topic"
CONF_MEDIA_IMAGE_URL_TOPIC = "media_image_url_topic"
CONF_MEDIA_POSITION_TOPIC = "media_position_topic"
CONF_MEDIA_TITLE_TOPIC = "media_title_topic"
CONF_NEXT_TRACK_TOPIC = "next_track_topic"
CONF_MEDIA_IMAGE_REMOTELY_ACCESSIBLE_TOPIC = "media_image_remotely_accessible_topic"
CONF_PAUSE_TOPIC = "pause_topic"
CONF_PLAY_TOPIC = "play_topic"
CONF_PREVIOUS_TRACK_TOPIC = "previous_track_topic"
CONF_REPEAT_SET_TOPIC = "repeat_set_topic"
CONF_REPEAT_STATE_TOPIC = "repeat_state_topic"
CONF_SEEK_TOPIC = "seek_topic"
CONF_SHUFFLE_SET_TOPIC = "shuffle_set_topic"
CONF_SHUFFLE_STATE_TOPIC = "shuffle_state_topic"
CONF_STOP_TOPIC = "stop_topic"
CONF_VOLUME_LEVEL_TOPIC = "volume_level_topic"
CONF_VOLUME_MUTE_COMMAND_TOPIC = "volume_mute_command_topic"
CONF_VOLUME_MUTE_STATE_TOPIC = "volume_mute_state_topic"
CONF_VOLUME_SET_TOPIC = "volume_set_topic"
CONF_VOLUME_STEP = "volume_step"
